import type { ResourceDescriptor } from '../registry/resources.js';

/**
 * FR-R3 — cursor-cli-mcp://resources/usage-patterns (API_SPEC §4.3).
 * Explains timeout behaviour and correct post-timeout workflow for any model or client.
 */
export const usagePatterns: ResourceDescriptor = {
  name: 'usage-patterns',
  uri: 'cursor-cli-mcp://resources/usage-patterns',
  description:
    'How to use cursor-cli-mcp correctly: timeout behaviour, post-timeout verification, task sizing, and multi-turn sessions',
  mimeType: 'text/markdown',
  content: [
    '# cursor-cli-mcp — Usage Patterns',
    '',
    'Read this before calling any tool. It explains behaviour that is non-obvious but critical to using this server correctly.',
    '',
    '---',
    '',
    '## 1. Timeout is not failure',
    '',
    'When `run_agent` is called with a long or complex task, the MCP client will often return:',
    '',
    '```',
    'MCP error -32001: Request timed out',
    '```',
    '',
    '**This does not mean the Cursor agent failed or stopped.**',
    '',
    'What actually happened:',
    '',
    '```',
    'MCP Client          MCP Server (this process)     Cursor Agent (subprocess)',
    '    │                        │                             │',
    '    │── run_agent ──────────>│                             │',
    '    │                        │── spawn ───────────────────>│',
    '    │                        │                             │ (working...)',
    '    │  [client timeout]      │                             │ (still working...)',
    '    │<── -32001 ─────────────│                             │ (still working...)',
    '    │  [connection dropped]  │                             │ (finishes, writes files)',
    '```',
    '',
    'The Cursor agent subprocess continues running and **writes all changes to disk**. The -32001 is the MCP client dropping its end of the connection — it has no effect on the agent process.',
    '',
    '---',
    '',
    '## 2. Post-timeout workflow',
    '',
    'After receiving -32001, follow this sequence **before doing anything else**:',
    '',
    '**Step 1 — Wait for the agent to finish**',
    'Give the agent time to complete. For typical coding tasks: 30–120 seconds after the timeout. Larger refactors may take longer.',
    '',
    '**Step 2 — Read the workspace files**',
    'Use your file reading tools to check what the agent actually produced. Do not assume it did nothing.',
    '',
    '**Step 3 — Run the project gate check**',
    "Run the project's lint, typecheck, build, and test commands to verify correctness:",
    '',
    '```bash',
    'npm run lint && npm run typecheck && npm run build && npm run test:unit',
    '```',
    '',
    '(Substitute the actual gate check for the project you are working on.)',
    '',
    '**Step 4 — Assess completeness**',
    '- If the work is complete and the gate passes: done.',
    '- If partial: call `run_agent` again with only the remaining work.',
    '- If nothing changed (rare): the agent may not have started — retry the full task.',
    '',
    '**What not to do:**',
    '- Do not re-implement the work inline. Check the files first.',
    '- Do not call `run_agent` again with the same prompt before checking — you may duplicate work.',
    '',
    '---',
    '',
    '## 3. Sizing tasks to avoid timeouts',
    '',
    'The MCP client timeout is typically 120 seconds. Tasks that reliably complete in that window:',
    '',
    '| Task type | Fits in 120s? |',
    '|-----------|--------------|',
    '| Single file edit or bug fix | Usually yes |',
    '| Adding one new feature to an existing file | Usually yes |',
    '| Multi-file refactor (3–5 files) | Sometimes |',
    '| Full feature implementation (10+ files) | Rarely — split it |',
    '| Batch of 20 fixes across the codebase | No — split into groups |',
    '',
    'When in doubt, break a large task into focused sub-tasks and call `run_agent` once per sub-task.',
    '',
    '---',
    '',
    '## 4. Choosing the right mode',
    '',
    '| Mode | What it does | When to use |',
    '|------|-------------|-------------|',
    '| `agent` (default) | Full read/write access — edits files, runs commands | Any implementation task |',
    '| `plan` | Read-only — analyses and plans, no edits | Before a large change; get a plan first |',
    '| `ask` | Read-only Q&A — explains code, answers questions | Understanding the codebase |',
    '',
    'Use `plan` before `agent` for large tasks: let the agent produce a plan, review it, then run `agent` to execute.',
    '',
    '---',
    '',
    '## 5. Multi-turn sessions',
    '',
    'For tasks that require continuity across multiple prompts:',
    '',
    '1. Call `session_create` to get a session ID.',
    '2. Call `session_resume` with the session ID and each follow-up prompt.',
    '',
    '> **Note:** `--resume --print` (non-interactive session continuation) is not officially documented by Cursor. The command runs but session context preservation is not guaranteed. For most tasks, a well-scoped single `run_agent` call is more reliable.',
    '',
    '---',
    '',
    '## 6. Security: workspace paths',
    '',
    "`workspace` and `worktree` paths must be in the server's `WORKSPACE_ALLOWLIST`. If a path is rejected with a `SECURITY` error, the operator must add it to `WORKSPACE_ALLOWLIST` in the MCP server config and restart.",
    '',
    'The allowlist uses **semicolons** as separators:',
    '',
    '```',
    'WORKSPACE_ALLOWLIST=/Users/you/projects;/Users/you/work',
    '```',
    '',
    '---',
    '',
    '## 7. Verifying the server is working',
    '',
    'Call `agent_status` first. It returns authentication status, binary path, and CLI version. If it returns `BINARY_NOT_FOUND`, the `AGENT_BINARY_PATH` env var is wrong or the binary is not installed.',
    '',
  ].join('\n'),
};
